### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by cfoellmann** [WolfgangFahl/PDFEmbed#12]
Hi,

I am helping myself with  manually defining composer data but adding a composer.json would make it easier to define how to fetch your extension

**Comment by WolfgangFahl** [comment]
@cfoellmann - a pull quest is welcome

**Comment by WolfgangFahl** [comment]
Do we need to do a tagged version?

**Comment by cfoellmann** [comment]
would be nice

**Comment by WolfgangFahl** [comment]
Also we might want to move back to the Wikimedia environment see https://phabricator.wikimedia.org/T312617 then the composer.json wouldn't need to be as complicated. I have invited you to this repository to help working on these.

**Comment by cfoellmann** [comment]
thanks.
I just pushed the tag and it works like a charm! 🥳
