### ISSUE TITLE
Incompatible with MW 1.39.4, 1.40

### ISSUE THREAD

**Issue by pav00** [WolfgangFahl/PDFEmbed#17]
It can be installed but instead of the file, only the black borders are shown, no file is displayed. iframe with https link is generated so it is some conflict with mediawiki core. During opening the page the file is embedded (iframed) on, it asks for saving the file which is highly undesirable behaviour.

**Comment by pa4080** [comment]
Probably some other extension cause the conflict and it reflects in someway on PDFEmbed, because within my wiki which I recently have updated to 1.40.1 the extension works as it is expected: [Test PDFEmbed with MW 1.40.1](https://wiki.metalevel.tech/wiki/Embed_PDF_Documents#Test_PDFEmbed_with_MW_1.40.1)

**Comment by pav00** [comment]
Thanks for pointing to the test page, after testing in more browsers I was
able to find where the root cause was.

In chromium it displayed correctly. In firefox there was the above
described issue. Firefox allows user settings in about:preferences#general
for content types and actions, three possible setting for PDF file
extension - Open in Firefox, Always ask, Save file. If the user has set up
anything different than Open in Firefox then the issue appears. Chromium
does not allow these user setting by default so the problem does not show.
Now the question is: is it possible for this extension to ignore/override
browser settings for handling pdf extension? Because it generates iframe
that is handled by browser, is there a way to force always display?

Thanks.

**Comment by pa4080** [comment]
This is a read-only property of the [`window.navigator`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator) object. According to MDN [`Navigator.pdfViewerEnabled`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/pdfViewerEnabled) is available on all major browsers, so I think it could be a good idea to provide some message to the user when the value is not true.

**Comment by WolfgangFahl** [comment]
Is there anything to be done. here? Otherwise i'll close this issue

**Comment by pa4080** [comment]
Hi, @WolfgangFahl, right now I do not have free time to spend to implement the feature proposed above. At all it could be a JavaScript that output a message in the place of the PDFEmbed container when `window.navigator.pdfViewerEnabled === false`

**Comment by pav00** [comment]
I think nothing to be done here, it is firefox issue.
