### ISSUE TITLE
embed_pdf_no_permission

### ISSUE THREAD

**Issue by matthias-oe** [WolfgangFahl/PDFEmbed#23]
Hello,
we have a docker instance of mediawiki 1.39.4 and try to use PDFEmbed (we clone https://github.com/WolfgangFahl/PDFEmbed.git and mount it to the extensions folder).

We want everybody (in our intranet) to be able to read all wiki pages. Login is necessary for editing.

We include PDFEmbed in our localSettings.php:
```
wfLoadExtension( 'PDFEmbed' );
//Allow all users the usage of the pdf tag
$wgGroupPermissions['*']['embed_pdf'] = true;
```
In "User group rights" we see "Embed PDFs into pages (embed_pdf)" for the groups "all", "Administrators" and "Users".

Currently we only have a test environment set up and only one Admin user (administrator). Neither the logged in Admin user nor a simple "guest" (group "*") is allowed to see PDFs: "The last editor of this page did not have the right to Embed PDFs into pages." (the german message is different: "Du bist nicht berechtigt PDF-Dateien einzubetten."). The last editor was "Admin", german "Du" is either the logged in Admin or a guest...

While I don't understand the need to consider the requestAction or the page's editor, ultimately there seems to be a problem with `$user instanceof UserIdentity` in PDFEmbed.hooks.php Line 125.

```
if (!( // $user instanceof UserIdentity &&
      MediaWikiServices::getInstance()->getPermissionManager()->userHasRight($user, 'embed_pdf')
```

Omitting this check (see above), pdf_embed works as expected. Any ideas?

Best regards
matthias-oe

PS: In which scenario are the additional rights checks required?

**Comment by tholzheim** [comment]
I have the same issue.
The problem is that `$user` is of type `User` and not `UserIdentity`

https://github.com/WolfgangFahl/PDFEmbed/blob/baa679c3d7bf3810aabef8d3180adb061b2782f2/PDFEmbed.hooks.php#L122

> $context->getUser() - the instance of [User](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:User.php) for the user the page is rendered for. [see](https://www.mediawiki.org/wiki/Manual:RequestContext.php) 

Changing the if condition to 
```php
if (!($user instanceof User &&
              MediaWikiServices::getInstance()->getPermissionManager()->userHasRight($user, 'embed_pdf')
        )) {
```
fixed it for me.

**Comment by bertrandgorge** [comment]
Thanks for the fix and the merge !
