### ISSUE TITLE
Can't display PDF

### ISSUE THREAD

**Issue by MarksenDE** [WolfgangFahl/PDFEmbed#9]
Hi Wolfgang,
great to see there's a simple PDF Tool to display PDFs. I choosed your tool because i'm hosting my mediawiki. After activating the plugin i'm not able to display a pdf file. My syntax is: "<pdf>File:abcd.pdf</pdf>" but after saving it doesn't show the pdf, it shows my main mediawiki screen :-) (looks like printscreen)

Would be great if you or any other have a hint/tipp for me.

BR  Mark

![mediawiki-pdf](https://user-images.githubusercontent.com/70513049/166727766-5391efe3-a128-46f9-832f-ad1332d97eb2.png)

**Comment by WolfgangFahl** [comment]
@MarksenDE  thanks for pointing this out - i fear this is an incompatiblity with the 1.37 version of Mediawiki. Our production systems are 1.35 LTS at this time and we'd have to test this in our docker environment or with your help. Feel free to get in touch with me via my website bitplan.com and we can arrange a session to check the details

**Comment by WolfgangFahl** [comment]
Please retry with the version 3.0.0 which was just released

**Comment by MarksenDE** [comment]
Hi Wolfgang,
just installed and tested new version:

Now i can see this
![12072022_pdf_test](https://user-images.githubusercontent.com/70513049/178443390-b7a06628-384d-4b2c-af25-8193bcdc44e7.png)

and every time i open this pdf it will be downloaded.

![12072022_version](https://user-images.githubusercontent.com/70513049/178443897-976dbe97-39e9-4e79-aef3-8dd4a6636ee4.png)

Hope that helps

Mark

**Comment by MarksenDE** [comment]
Hi Wolfgang, it works! 

Currently in Microsoft Edge (Version 102.0.1245.44) it works, but in Firefox (102) not, still downloading instead of showing. Maybe i have to change some settings ...

BR  Mark


**Update:** just change in FF under Settings -> Applications -> how to handle PDF files (instead of downloading) Everything is fine now, please close the issue and thanks for your help!

**Comment by pa4080** [comment]
Here is an reference about this: [View PDF files in Firefox or choose another viewer](https://support.mozilla.org/en-US/kb/view-pdf-files-firefox-or-choose-another-viewer?redirectslug=view-pdf-files-firefox&redirectlocale=en-US).

**Comment by WolfgangFahl** [comment]
@metalevel-tech  - thx for this success - closing
